name: GitHub Action Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 23f2002954@ds.study.iitm.ac.in
        run: echo "Hello, world!"
